# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='android',
            old_name='uuid',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='android',
            name='modelid',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='android',
            name='operator',
            field=models.CharField(default='k', max_length=80),
            preserve_default=False,
        ),
    ]
